# Generated by Django 4.0.5 on 2022-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='massage_files/'),
        ),
    ]
