# Generated by Django 4.0.5 on 2022-07-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0003_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='rusume',
            new_name='resume',
        ),
    ]
