# Generated by Django 4.0.5 on 2022-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0004_rename_rusume_apply_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(default='In Progress', max_length=70),
        ),
    ]
