# Generated by Django 4.0.5 on 2022-07-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('massages', '0005_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.vacancy'),
        ),
    ]
