# Generated by Django 3.1.14 on 2022-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0007_auto_20220705_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='massage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
