# Generated by Django 3.1.14 on 2022-07-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0008_apply_massage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
