# Generated by Django 4.0.5 on 2022-07-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0009_delete_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='massage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
