# Generated by Django 4.0.5 on 2022-07-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='bio',
        ),
    ]
