# Generated by Django 3.1.14 on 2022-07-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220705_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_employer',
        ),
    ]
