# Generated by Django 3.1.14 on 2022-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220706_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
