# Generated by Django 3.1.14 on 2022-07-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220707_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary_for',
        ),
    ]
