# Generated by Django 3.1.14 on 2022-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_delete_hire'),
        ('worker', '0002_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='job.Category'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
