# Generated by Django 3.1.14 on 2022-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20220707_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='cost_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
