# Generated by Django 3.1.14 on 2022-07-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20220707_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='worker.resume'),
        ),
    ]
