# Generated by Django 4.0.5 on 2022-07-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_hire_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
