# Generated by Django 3.1.14 on 2022-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220705_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
