# Generated by Django 3.1.14 on 2022-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220705_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='applications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
