# Generated by Django 3.1.14 on 2022-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_vacancy_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
