# Generated by Django 3.1.14 on 2022-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='active',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
