# Generated by Django 3.1.14 on 2022-07-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_hire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hire',
        ),
    ]
